language: cpp
before_script:
- sudo apt-get install libgtest-dev
- cd /usr/src/gtest
- sudo apt-get install cmake
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uzazicam:$BINTRAY_API_KEY "https://api.bintray.com/content/zazicam/repo1/package1/$TRAVIS_BUILD_NUMBER/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
